name: Build Images from Istio

on:
   push:
     branches:
       - master

jobs:
  Build-Application:
    runs-on: ubuntu-latest
    env:
      # REGISTRY: ghcr.io
      REGISTRY: exemplo.azurecr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Split the owner and name of a repository
        uses: owner/github-split-repo-owner-name-action@v1.0.0
      
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: exemplo
          password: ${{ secrets.ACRPASS }}
          login-server: ${{ env.REGISTRY }}

      - name: Build and Push the Kiali application image to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          tags: ${{ env.REGISTRY }}/${{ env.GITHUB_REPO_OWNER }}/kiali:v1.59
          push: true
          file: dockerfiles/addons/kiali/Dockerfile
      
      - name: Build and Push the Jaeger application image to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          tags: ${{ env.REGISTRY }}/${{ env.GITHUB_REPO_OWNER }}/jaegertracing/all-in-one:1.35
          push: true
          file: dockerfiles/addons/jaeger/Dockerfile
      
      - name: Build and Push the Grafana application image to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          tags: ${{ env.REGISTRY }}/${{ env.GITHUB_REPO_OWNER }}/grafana:9.0.1-ubuntu
          push: true
          file: dockerfiles/addons/grafana/Dockerfile
      
      - name: Build and Push the Prometheus application image to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          tags: ${{ env.REGISTRY }}/${{ env.GITHUB_REPO_OWNER }}/prometheus:v2.34.0
          push: true
          file: dockerfiles/addons/prometheus/Dockerfile

      - name: Build and Push the Istio Proxy application image to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          tags: ${{ env.REGISTRY }}/${{ env.GITHUB_REPO_OWNER }}/istio/proxyv2:1.16.1
          push: true
          file: dockerfiles/istio-proxy/Dockerfile
      
      - name: Build and Push the Istio Pilot application image to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          tags: ${{ env.REGISTRY }}/${{ env.GITHUB_REPO_OWNER }}/istio/pilot:1.16.1
          push: true
          file: dockerfiles/istiod/Dockerfile